name: Fetch Data

on:
  push:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository names from JSON file
        id: get-repo-names
        run: |
          curl -sSL -o repos.json https://raw.githubusercontent.com/OWASP/owasp.github.io/main/_data/projects.json
          echo "::set-output name=repo-names::$(jq -r '.[].name' repos.json)"
        
      - name: Fetch data from GitHub GraphQL API
        uses: JasonEtco/query-github-graphql@v1.x
        with:
          query: |
            query($name: String!) {
              repository(owner: "OWNER", name: $name) {
                name
                description
                stargazerCount
                primaryLanguage {
                  name
                }
                licenseInfo {
                  name
                }
              }
            }
          token: ${{ secrets.ACCESS_TOKEN }}
          name: ${{ fromJSON(outputs.get-repo-names)[$matrix.repo-name] }}
        id: data
        env:
          MATRIX_REPO_NAME: ${{ fromJSON(outputs.get-repo-names) }}
        
      - name: Write data to JSON file
        run: |
          echo '${{ steps.data.outputs.data }}' >> data.json

      - name: Commit data to repository
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add data.json
          git commit -m "Update data"
          git push origin main
        if: always()

    outputs:
      get-repo-names: ${{ steps.get-repo-names.outputs.repo-names }}

    strategy:
      matrix:
        repo-name: ${{ join(fromJSON(outputs.get-repo-names), ',') }}

